### PR TITLE
add function to find form letters from comments

### PR DESCRIPTION
**Pull request by jgibson517**
@abejburton couple questions for you on this:
- is `df_rep_form` the dataframe containing all comments with similarity scores > 0.95, ie comments that may be form letters?
- also, is `df_rep_paraphrase` the right df to use to count the number of unique comments, excluding form letters?
- do you think we should we store the condensed form letters with the other representative comments in `RepComments` or have a separate attribute?
- what should our threshold for including a form letter be: only include if there are at least 10 like comments? or some other metric?

### CODE REVIEW

**Comment by abejburton** [comment]
`df_rep_form` and `df_rep_paraphrase` are the dataframes holding the representative comments only. `df_form_letter` and `df_paraphrase` are the only dataframes with all comments, the problem is that they are dataframes with each row representing a comment pair with a similarity score. So you could have up to n^2 instead of n rows in the dataframes. 

So to calculate total comments (form or unique) the easiest way might be to sum the number of comments represented in `df_rep_form` and `df_rep_paraphrase`.

**Comment by abejburton** [comment]
On the subject of where to store the condensed  representative form letters - seems like those should replace `df_rep_form` in the representative comments. Because that's really what we want to display to the user. Right now 'df_rep_form' is just ordered by number of comments represented but the condensed version is better.

**Comment by abejburton** [comment]
Not sure I get the full context on when to include form letters, lets talk about that

**Comment by jgibson517** [comment]
@abejburton added `count_unique_comments` to compute the number of unique comments after you call `comment_similarity`, solves the issue where the number of unique comment is always equal to the number of representative comments which is currently true in postgres

**Review by abejburton — APPROVED** [review]

**Pull request merged**
