### PR TITLE
Made edits to 'collect.md' to reflect changes made in code, added one…

### PR DESCRIPTION
**Pull request by GregoryHo88**
… more example

### CODE REVIEW

**Review by rezarzky — APPROVED** [review]
LGTM

**Comment by claireboyd** [comment]
@GregoryHo88 i'm going to add some stuff to this branch, so can tag you when it's ready to review/merge!

**Comment by GregoryHo88** [comment]
> @GregoryHo88 i'm going to add some stuff to this branch, so can tag you when it's ready to review/merge!

Roger that @claireboyd

**Comment by claireboyd** [comment]
@GregoryHo88 good to merge if my edits look okay with you!

**Pull request merged**
