### PR TITLE
Create constants file

### PR DESCRIPTION
**Pull request by andrewjtdunn**
create utils folder and constants file, which pulls using dotenv package

### CODE REVIEW

**Comment by abejburton** [comment]
All the changes look good to me. The linter is catching unused imports that need to be changed before merging this PR

**Comment by andrewjtdunn** [comment]
@abejburton where are those imports? I'm finding it difficult to trace where in the code is causing that issue

**Comment by abejburton** [comment]
I found the issue - the develop branch has code that is not passing the linter that was merged from frontend over the weekend. I will fix that code in the develop branch and rerun the tests this afternoon.

**Comment by abejburton** [comment]
Linter changes made in pull request #22, this should pass now

**Review by abejburton — APPROVED** [review]

**Pull request merged**
