### PR TITLE
new version of home with content

### PR DESCRIPTION
**Pull request by claireboyd**

### CODE REVIEW

**Comment by jchristensonCHI** [comment]
LGTM!

**Comment by jchristensonCHI** [comment]
Looks re #

> Screenshot 2024-05-20 at 11 44 25 AM

Only thing is it a little hard to see the search button hear since they are both blue, great work overall though!

**Comment by jchristensonCHI** [comment]
If you want me to approve can do!

**Comment by claireboyd** [comment]
awesome ty for the review! definitely - i was planning on walking through it/asking for feedback during our meeting then reviewing/merging to main when the more final draft is ready!

**Review by jchristensonCHI — APPROVED** [review]
LGTM!

**Pull request merged**
